webtalk_init -webtalk_dir C:\\Users\\OAkun\\Desktop\\CECS460Micro\\DetMicroBlazeLec\\DetMicroBlazeLec.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-04-02 20:47:57" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ocgk7trhr5qad60km9c4jj7ide" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.354 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1617420052856" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1617420052856"
webtalk_add_data -client sdk -key uid -value "1617420133776" -context "sdk\\\\bsp/1617420133776"
webtalk_add_data -client sdk -key hwid -value "1617420052856" -context "sdk\\\\bsp/1617420133776"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1617420133776"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1617420133776"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1617420133776"
webtalk_add_data -client sdk -key uid -value "1617420138245" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key hwid -value "1617420052856" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key bspid -value "1617420133776" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key projSize -value "102.8984375" -context "sdk\\\\application/1617420138245"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1617421677345"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1617421677345"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1617421677345"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1617421677345"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1617421677345"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1617421677345"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1617421677345"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1617421677345"
webtalk_transmit -clientid 2700734878 -regid "" -xml C:\\Users\\OAkun\\Desktop\\CECS460Micro\\DetMicroBlazeLec\\DetMicroBlazeLec.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\OAkun\\Desktop\\CECS460Micro\\DetMicroBlazeLec\\DetMicroBlazeLec.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\OAkun\\Desktop\\CECS460Micro\\DetMicroBlazeLec\\DetMicroBlazeLec.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
