# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0.xci
# IP: The module: 'DeterminantMicroBlaze_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DeterminantMicroBlaze_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DeterminantMicroBlaze_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DeterminantMicroBlaze_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0.xci
# IP: The module: 'DeterminantMicroBlaze_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DeterminantMicroBlaze_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DeterminantMicroBlaze_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/OAkun/Desktop/CECS460Micro/DetMicroBlazeLec/DetMicroBlazeLec.srcs/sources_1/bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DeterminantMicroBlaze_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
